version: '3.7'

services:
  database:
    image: postgres:alpine
    ports: 
      - 127.0.0.1:5437:5432
    environment:
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_DB: "goForum"
  app:
    build: .
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - database
    